title: artBangall

tagline: >
  artBangall is a pop-up exhibition opening on Saturday, June 2nd, in the hamlet
  of Bangall in the Hudson Valley. The show will feature artwork by thirty five
  emerging artists and take place in a vacant former restaurant.

url: https://artbangall.com

socialimg: /img/social.jpg

sass:
 style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
